// <auto-generated />
using System;
using Bowling.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bowling.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260407114745_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bowling.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BowlingLaneId")
                        .HasColumnType("int");

                    b.Property<int>("Customersid")
                        .HasColumnType("int");

                    b.Property<int>("HoursToPlay")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BowlingLaneId");

                    b.HasIndex("Customersid");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Bowling.Models.BowlingHall", b =>
                {
                    b.Property<int>("BowlingHallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BowlingHallId"));

                    b.Property<string>("BowlingHallName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BowlingHallId");

                    b.ToTable("BowlingHalls");
                });

            modelBuilder.Entity("Bowling.Models.BowlingLane", b =>
                {
                    b.Property<int>("BowlingLaneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BowlingLaneId"));

                    b.Property<int>("BowlingHallId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.HasKey("BowlingLaneId");

                    b.HasIndex("BowlingHallId");

                    b.ToTable("BowlingLanes");
                });

            modelBuilder.Entity("Bowling.Models.Customer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("BookingCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsMember")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Bowling.Models.Booking", b =>
                {
                    b.HasOne("Bowling.Models.BowlingLane", null)
                        .WithMany("Bookings")
                        .HasForeignKey("BowlingLaneId");

                    b.HasOne("Bowling.Models.Customer", "Customers")
                        .WithMany("Bookings")
                        .HasForeignKey("Customersid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Bowling.Models.BowlingLane", b =>
                {
                    b.HasOne("Bowling.Models.BowlingHall", null)
                        .WithMany("BookingLanes")
                        .HasForeignKey("BowlingHallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bowling.Models.BowlingHall", b =>
                {
                    b.Navigation("BookingLanes");
                });

            modelBuilder.Entity("Bowling.Models.BowlingLane", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Bowling.Models.Customer", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
